routes/web.php
<?php

use App\Http\Controllers\Admin\SendNotificationController;
use App\Http\Controllers\DrinkController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\CheersController;
use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\InvoicesController;
use App\Http\Controllers\Admin\UploaderController;
use App\Http\Controllers\RegisterVenuesController;
use App\Http\Controllers\Admin\SliderOneController;
use App\Http\Controllers\Admin\SliderTwoController;
use App\Http\Controllers\Company\MyCompanyController;
use App\Http\Controllers\Admin\Venues\TypesController;
use App\Http\Controllers\Admin\Venues\OffersController;
use App\Http\Controllers\Admin\Venues\VenuesController;
use App\Http\Controllers\Admin\AdministratorsController;
use App\Http\Controllers\Admin\UserFeesReportController;
use App\Http\Controllers\Admin\Venues\CalendarController;
use App\Http\Controllers\Admin\Venues\PurchasesController;
use App\Http\Controllers\Admin\Products\ProductsController;
use App\Http\Controllers\Admin\Settings\PasswordController;
use App\Http\Controllers\Admin\Settings\SettingsController;
use App\Http\Controllers\Admin\AdministrativeDataController;
use App\Http\Controllers\Admin\Companies\CompaniesController;
use App\Http\Controllers\Admin\ExpiredDrinksReportController;
use App\Http\Controllers\Admin\Products\CategoriesController;
use App\Http\Controllers\Admin\Venues\PremiumDrinksController;
use App\Http\Controllers\Venue\VenueController as MyVenueController;
use App\Http\Controllers\Admin\Api\OrdersController as ApiOrdersController;
use App\Http\Controllers\Venue\OffersController as MyVenueOffersController;
use App\Http\Controllers\Venue\OrdersController as MyVenueOrdersController;
use App\Http\Controllers\Admin\Api\InvoicesController as ApiInvoicesController;
use App\Http\Controllers\Venue\CalendarController as MyVenueCalendarController;
use App\Http\Controllers\Venue\InvoicesController as MyVenueInvoicesController;
use App\Http\Controllers\Admin\Venues\OrdersController as VenueOrdersController;
use App\Http\Controllers\Admin\Venues\InvoicesController as VenueInvoicesController;
use App\Http\Controllers\Admin\Venues\ReviewsController as VenueReviewsController;
use App\Http\Controllers\Venue\PremiumDrinksController as MyVenuePremiumDrinksController;
use App\Http\Controllers\Admin\DigitalEvents\CardsController as DigitalEventsCardsController;
use App\Http\Controllers\Admin\DigitalEvents\EventsController as DigitalEventsEventsController;
use App\Http\Controllers\Admin\DigitalEvents\LabelsController as DigitalEventsLabelsController;
use App\Http\Controllers\Admin\ScheduledPushNotificationsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('pdf-invoices', function () {
    return view('admin.pdf-invoices.test-admin');
});

Route::get('venues/register', [RegisterVenuesController::class, 'showRegisterVenueForm'])->name('venues.register');
Route::post('venues', [RegisterVenuesController::class, 'store'])->name('venues.store');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', [HomeController::class, 'index'])->name('dashboard');

    Route::group(['middleware' => 'role:super-admin|admin', 'prefix' => 'admin'], function () {
        //Administrators
        Route::resource('administrators', AdministratorsController::class, ['except' => 'destroy', 'as' => 'admin']);
        Route::delete('administrators/{administrator?}', [AdministratorsController::class, 'destroy'])->name('admin.administrators.destroy');

        Route::resource('users', UsersController::class, ['except' => 'destroy', 'as' => 'admin']);
        Route::delete('users/{user?}', [UsersController::class, 'destroy'])->name('admin.users.destroy');
        Route::get('users/{user}/gifted-items/{cart}', [UsersController::class, 'showGiftedItems'])->name('admin.users.showGiftedItems');
        Route::get('users/{user}/purchased-items/{cart}', [UsersController::class, 'showPurchasedItems'])->name('admin.users.showPurchasedItems');

        //User Purchased And Gifted API
        Route::post('purchased', [UsersController::class, 'getPurchased'])->name('admin.users.getPurchased');
        Route::post('users/{user}/purchased-items/{cart}', [UsersController::class, 'getPurchasedItems'])->name('admin.users.getPurchasedItems');
        Route::post('gifted', [UsersController::class, 'getGifted'])->name('admin.users.getGifted');
        Route::post('users/{user}/gidted-items/{cart}', [UsersController::class, 'getGiftedItems'])->name('admin.users.getGiftedItems');

        //Venues
        Route::resource('venues', VenuesController::class, ['except' => 'destroy', 'as' => 'admin']);
        Route::delete('venues/{venue?}', [VenuesController::class, 'destroy'])->name('admin.venues.destroy');

        Route::put('venues/{venue}/status', [VenuesController::class, 'updateStatus'])->name('admin.venues-status.update');

        //Venues Api
        Route::post('get-venues', [VenuesController::class, 'getVenues'])->name('getVenues');

        //Venue slider one
        Route::get('slider-one', [SliderOneController::class, 'index'])->name('admin.slider-one.index');
        Route::post('slider-one', [SliderOneController::class, 'getVenues'])->name('admin.slider-one.getVenues');
        Route::post('slider-one/add-venue', [SliderOneController::class, 'addVenue'])->name('admin.slider-one.addVenue');
        Route::post('slider-one/remove-venue', [SliderOneController::class, 'removeVenue'])->name('admin.slider-one.removeVenue');
        Route::patch('slider-one', [SliderOneController::class, 'update'])->name('admin.slider-one.update');

        //Venue slider two
        Route::get('slider-two', [SliderTwoController::class, 'index'])->name('admin.slider-two.index');
        Route::post('slider-two', [SliderTwoController::class, 'getVenues'])->name('admin.slider-two.getVenues');
        Route::post('slider-two/add-venue', [SliderTwoController::class, 'addVenue'])->name('admin.slider-two.addVenue');
        Route::post('slider-two/remove-venue', [SliderTwoController::class, 'removeVenue'])->name('admin.slider-two.removeVenue');
        Route::patch('slider-two', [SliderTwoController::class, 'update'])->name('admin.slider-two.update');

        //Companies
        Route::resource('companies', CompaniesController::class, ['except' => 'destroy', 'as' => 'admin']);
        Route::delete('companies/{company?}', [CompaniesController::class, 'destroy'])->name('admin.companies.destroy');

        //Company Api
        Route::post('get-companies', [CompaniesController::class, 'getCompanies'])->name('getCompanies');

        //Purchases
        Route::get('purchases', [PurchasesController::class, 'Index'])->name('admin.purchases.index');
        Route::get('purchases/{id}', [PurchasesController::class, 'show'])->name('admin.purchases.show');
        Route::get('purchases/{id}/drinks', [PurchasesController::class, 'drinks'])->name('admin.purchases.drinks');

        //Purchases Api
        Route::post('get-purchase/{id}', [PurchasesController::class, 'getPurchase'])->name('getPurchase');
        Route::post('get-purchases', [PurchasesController::class, 'getPurchases'])->name('getPurchases');
        Route::post('get-purchases/items', [PurchasesController::class, 'getPurchaseItems'])->name('getPurchaseItems');

        Route::group(['as' => 'admin.'], function () {
            Route::resource('products', ProductsController::class, ['except' => ['show']]);
            Route::resource('product-categories', CategoriesController::class, ['except' => ['show']]);
        });

        //Venue Premium Drinks
        Route::resource('venues/{venue}/premium-drinks', PremiumDrinksController::class, ['except' => ['show', 'destroy'], 'as' => 'admin.venue'])->parameters([
            'premium-drinks' => 'drink',
        ]);
        Route::delete('venues/{venue}/premium-drinks/{drink?}', [PremiumDrinksController::class, 'destroy'])->name('admin.venue.premium-drinks.destroy');

        //Two Per One drinks
        Route::resource('venues/{venue}/offers', OffersController::class, ['except' => ['show', 'destroy'], 'as' => 'admin.venue']);
        Route::delete('venues/{venue}/offers/{offer?}', [OffersController::class, 'destroy'])->name('admin.venue.offers.destroy');

        //Calendar
        Route::get('venues/{venue}/calendar', [CalendarController::class, 'index'])->name('admin.venue.calendar.index');
        Route::get('venues/{venue}/offers-calendar', [CalendarController::class, 'getOffers'])->name('admin.venue.calendar.offers');

        //Settings
        Route::put('settings/password/{user}', [PasswordController::class, 'update'])->name('admin.settings.password.update');

        Route::get('settings', [SettingsController::class, 'index'])->name('admin.settings.index');
        Route::get('settings/create', [SettingsController::class, 'create'])->name('admin.settings.create');
        Route::get('settings/{setting}/edit', [SettingsController::class, 'edit'])->name('admin.settings.edit');
        Route::patch('settings/{setting}', [SettingsController::class, 'update'])->name('admin.settings.update');

        //Administrative Data
        Route::get('administrative-data/edit', [AdministrativeDataController::class, 'edit'])->name('admin.administrative-data.edit');
        Route::patch('administrative-data/update', [AdministrativeDataController::class, 'update'])->name('admin.administrative-data.update');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * @OA\Schema(
 *    @OA\Property(property="id", type="integer", example=1),
 *    @OA\Property(property="user_id", type="integer", example=1),
 *    @OA\Property(property="name", type="string", example="Company name"),
 *    @OA\Property(property="email", type="string", example="example@email.com"),
 *    @OA\Property(property="city", type="string", example="Roma"),
 *    @OA\Property(property="address", type="string", example="Via Longhena 52"),
 *    @OA\Property(property="phone_number", type="string", example="+3928478327"),
 *    @OA\Property(property="image_url", type="string", nullable=true, example=null),
 *    @OA\Property(property="status", type="boolean", example=true),
 *    @OA\Property(property="fiscal_name", type="string", example="OpenBar Group"),
 *    @OA\Property(property="event_setup_fee", type="integer", example=5),
 *    @OA\Property(property="event_drink_fee", type="integer", example=7),
 *    @OA\Property(property="event_venue_fee", type="integer", example=4),
 *    @OA\Property(property="fiscal_address", type="string", example="00020 Via Longhena 52, Rome"),
 *    @OA\Property(property="fiscal_city", type="string", example="Rome"),
 *    @OA\Property(property="fiscal_prov", type="string", example="91-6215272"),
 *    @OA\Property(property="fiscal_cap", type="string", example="35-7697382"),
 *    @OA\Property(property="fiscal_vat", type="string", example="34-5604738"),
 *    @OA\Property(property="fiscal_code", type="string", example="95-2120162"),
 *    @OA\Property(property="sdi_code", type="string", example="01-9883216"),
 *    @OA\Property(property="certified_email", type="string", example="example@email.com"),
 *    @OA\Property(property="bic", type="string", example="ABCOITMM"),
 *    @OA\Property(property="iban", type="string", example="IT60X0542811101000000123456"),
 *    @OA\Property(property="created_at", type="string", example="2022-01-01T13:00:00.000000Z"),
 *    @OA\Property(property="updated_at", type="string", example="2022-01-01T13:00:00.000000Z"),
 * )
 */
class Company extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $casts = [
        'status' => 'boolean',
    ];

    public static function boot()
    {
        parent::boot();

        self::deleting(function($company) {
            $company->user()->delete();
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault();
    }

    public function invoice()
    {
        return $this->morphMany(Invoice::class, 'subject');
    }

    public function imageUrl()
    {
        return $this->image_url ? asset('uploads/' . $this->image_url) : null;
    }

    public function getImageUrlAttribute($value): ?string
    {
        return $value ? asset('uploads/' . $value) : null;
    }
}

app/Http/Controllers/Admin/Companies/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin\Companies;

use App\Models\Company;
use App\Jobs\StoreCompany;
use App\Jobs\UpdateCompany;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyRequest;
use Yajra\DataTables\Facades\DataTables;

class CompaniesController extends Controller
{
    public function index()
    {
        return view('admin.companies.index');
    }

      /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.companies.create');
    }

        /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        $this->dispatchNow(new StoreCompany($request));

        return redirect()
            ->route('admin.companies.index')
            ->with('flash', 'Company has created successfully!');
    }

    public function show(Company $company)
    {
        return view('admin.companies.show', compact('company'));
    }

        /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('admin.companies.edit', compact('company'));
    }

        /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, Company $company)
    {
        $this->dispatchNow(new UpdateCompany($request, $company));

        return redirect()
            ->route('admin.companies.index')
            ->with('flash', 'Company has updated successfully!');
    }

     /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();

        return redirect()
            ->route('admin.companies.index')
            ->with('flash', 'Company has deleted successfully!');
    }

    public function getCompanies(Request $request)
    {
        if ($request->ajax()) {
            $query = Company::query();

            return Datatables::eloquent($query)
                ->editColumn('created_at', function ($item) {
                    return $item->created_at
                        ? date( config('rubik.base.datetime_format'), strtotime($item->created_at) )
                        : '';
                })
                ->addColumn('actions', function () {
                    return null;
                })
                ->toJson();
        }
    }
}

app/Http/Controllers/Company/MyCompanyController.php
<?php

namespace App\Http\Controllers\Company;

use App\Models\Company;
use App\Jobs\UpdateCompany;
use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyRequest;

class MyCompanyController extends Controller
{
    public function show()
    {
        $company = auth()->user()->company;

        return view('company.show', compact('company'));
    }

    public function edit()
    {
        $company = auth()->user()->company;

        return view('company.edit', compact('company'));
    }

    public function update(CompanyRequest $request)
    {
        $company = auth()->user()->company;

        $this->dispatchNow(new UpdateCompany($request, $company));

        return redirect()
            ->route('company.show')
            ->with('flash', 'Company has updated successfully!');
    }
}

resources/views/admin/companies/create.blade.php
@extends('layouts.app')

@include('admin.metronic.layout.partials.breadcrumbs', [
    'breadcrumbs' => [
        ['title' => 'Dashboard', 'url' => route('dashboard')],
        ['title' => 'Companies', 'url' => route('admin.companies.index')],
        ['title' => 'Create']
    ]
])

@section('content')
    <form
        class="form"
        id="validate_company_request"
        action="{{ route('admin.companies.store') }}"
        method="POST"
        enctype="multipart/form-data"
    >
    @csrf
        <!--begin::Content-->
        <div class="col-lg-12">
            <!--begin::Card-->
            <div class="card card-custom">
                <!--begin::Header-->
                <div class="card-header py-3">
                    <div class="card-title align-items-start flex-column">
                        <h3 class="card-label font-weight-bolder text-dark">Create Company</h3>
                    </div>
                </div>
                <!--end::Header-->
                <!--begin::Form-->
                @include('admin.companies.components.form', [
                    'company' => new App\Models\Company,
                    'action' => 'Create',
                ])
                <!--end::Form-->
            </div>
            <!--end::Card-->
        </div>
        <!--end::Content-->
    </form>
@endsection

@push('scripts')
    <script src="{{ asset('assets/js/pages/crud/file-upload/image-input.js') }}"></script>

        <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CompanyRequest', '#validate_company_request'); !!}
@endpush

resources/views/admin/companies/edit.blade.php
@extends('layouts.app')

@include('admin.metronic.layout.partials.breadcrumbs', [
    'breadcrumbs' => [
        ['title' => 'Dashboard', 'url' => route('dashboard')],
        ['title' => 'Companies', 'url' => route('admin.companies.index')],
        ['title' => 'Edit']
    ]
])

@section('content')
    <form
        class="form"
        action="{{ route('admin.companies.update', $company->id) }}"
        method="POST"
        id="validate_company_request"
        enctype="multipart/form-data"
    >
    @csrf
    @method('PATCH')
        <!--begin::Content-->
        <div class="col-lg-12 mb-5">
            <!--begin::Card-->
            <div class="card card-custom">
                <!--begin::Header-->
                <div class="card-header py-3">
                    <div class="card-title align-items-start flex-column">
                        <h3 class="card-label font-weight-bolder text-dark">Edit Company</h3>
                    </div>
                </div>
                <!--end::Header-->
                <!--begin::Form-->
                @include('admin.companies.components.form', [
                    'action' => 'Save Changes',
                ])
                <!--end::Form-->
            </div>
            <!--end::Card-->
        </div>
        <!--end::Content-->
    </form>

    <!--begin::Content-->
    <div class="col-lg-12">
        <!--begin::Card-->
        <div class="card card-custom">
            <!--begin::Header-->
            <div class="card-header py-3">
                <div class="card-title align-items-start flex-column">
                    <h3 class="card-label font-weight-bolder text-dark">Password Settings</h3>
                    <span class="text-muted font-weight-bold font-size-sm mt-1">Update the password used for logging into company account.</span>
                </div>
            </div>
            <!--end::Header-->
            <!--begin::Form-->
            <form
                class="form"
                id="password_validation"
                action="{{ route('admin.settings.password.update', $company->user->id) }}"
                method="POST"
                enctype="multipart/form-data"
            >
                @method('PUT')
                @csrf
                <div class="card-body">
                    @include('admin.administrators.components.password', [
                        'password' => 'New password'
                    ])

                    <div class="card-footer text-right">
                        <button type="button" class="btn btn-light-primary font-weight-bold">Cancel</button>
                        <button type="submit" class="btn btn-primary font-weight-bold">Save Changes</button>
                    </div>
                    <div class="col-lg-5 offset-3">
                        @if (count($errors))
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $message)
                                    <li class="ml-5">{{ $message }}</li>
                                @endforeach
                            </ul>
                        @endif
                   </div>
                </div>
            <!--end::Form-->
            </form>
        </div>
        <!--end::Card-->
    </div>
    <!--end::Content-->
@endsection

@push('scripts')
    <script src="{{ asset('js/form/password-validate.js') }}"></script>
    <script src="{{ asset('assets/js/pages/crud/file-upload/image-input.js') }}"></script>
     <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CompanyRequest', '#validate_company_request'); !!}
@endpush

resources/views/admin/companies/index.blade.php
@extends('layouts.app')

@include('admin.metronic.layout.partials.breadcrumbs', [
    'breadcrumbs' => [
        ['title' => 'Dashboard', 'url' => route('dashboard')],
        ['title' => 'Companies']
    ]
])

@section('content')
    <!--begin::Card-->
    <div class="card card-custom">
        <div class="card-header flex-wrap py-5">
            <div class="card-title">
                <h3 class="card-label">Companies</h3>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="{{ route('admin.companies.create') }}" class="btn btn-primary font-weight-bolder">
                    <span class="svg-icon svg-icon-md">
                    <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <rect x="0" y="0" width="24" height="24" />
                            <circle fill="#000000" cx="9" cy="15" r="6" />
                            <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                            </g>
                        </svg>
                        <!--end::Svg Icon-->
                    </span>Create
                </a>
                <!--end::Button-->
            </div>
        </div>
        <div class="card-body">
            <!--begin: Datatable-->
            <table class="table table-bordered table-hover table-checkable mt-10" id="company">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>City</th>
                        <th>Status</th>
                        <th>Phone</th>
                        <th>Created At</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>City</th>
                        <th>Status</th>
                        <th>Phone</th>
                        <th>Created At</th>
                        <th>Actions</th>
                    </tr>
                </tfoot>
            </table>
            <!--end: Datatable-->
        </div>
    </div>
    <div class="modal fade" id="deleteCompany" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
        @include('admin.companies.components.modals.delete')
    </div>
@endsection

@push('scripts')
    <script>
        var getCompanies = {!! json_encode(route('getCompanies')) !!}
        var companiesEdit = {!! json_encode(route('admin.companies.edit', ':company')) !!};
        var companiesShow = {!! json_encode(route('admin.companies.show', ':company')) !!};
    </script>

    <script src="{{ asset('js/form/form-validate.js') }}"></script>
    <script src="{{ asset('js/admin/datatables/company.js') }}"></script>

    <script>
        $(document).on("click", "#delete-company", function () {
            var id = $(this).data("id");
            if (id) {
                $('form').attr('action', function(i, value) {
                    return value + "/" + id;
                });
            }
        });
    </script>
@endpush